#ifndef MODERN_CPP_PROJECT_VERSION_HPP
#define MODERN_CPP_PROJECT_VERSION_HPP

#define MODERN_CPP_PROJECT_VERSION "1.0.0"

#define MODERN_CPP_PROJECT_MAJOR_VERSION 1
#define MODERN_CPP_PROJECT_MINOR_VERSION 0
#define MODERN_CPP_PROJECT_PATCH_VERSION 0

#endif  // MODERN_CPP_PROJECT_VERSION_HPP

