#ifndef CPPGIT_VERSION_HPP
#define CPPGIT_VERSION_HPP

#define CPPGIT_VERSION "1.0.0"

#define CPPGIT_MAJOR_VERSION 1
#define CPPGIT_MINOR_VERSION 0
#define CPPGIT_PATCH_VERSION 0

#endif  // CPPGIT_VERSION_HPP

